server:
  port: 8081
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:8080/USER_INFO
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

