USE AUTHENTICATION;

CREATE TABLE IF NOT EXISTS BUILDING (
    BUILDING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    NUM_FLOORS INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ROOM (
    ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUILDING_ID BIGINT NOT NULL,
    ROOM_NUMBER VARCHAR(50) NOT NULL,
    FLOOR_NUMBER INT,
    ROOM_TYPE VARCHAR(50),
    PRICE DECIMAL(10,2),
    STATUS VARCHAR(8) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ROOM_BUILDING_ID_FK FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING(BUILDING_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RENTAL (
    RENTAL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ROOM_ID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    STATUS VARCHAR(8) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT RENTAL_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    CONSTRAINT RENTAL_ROOM_ID_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID) ON DELETE CASCADE
);
