DROP SCHEMA IF EXISTS USER_INFO;

CREATE SCHEMA USER_INFO;

USE USER_INFO;

CREATE TABLE ACCOUNT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(40) NOT NULL,
    -- WITH MD5:
    -- THE HASH IS ALWAYS 128 BITS.
    -- IF YOU ENCODE IT AS A HEXDECIMAL STRING YOU CAN ENCODE 4 BITS PER CHARACTER,
    -- GIVING 32 CHARACTERS
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(40),
    CREATED_ON TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(40),
    LAST_MODIFIED_ON TIMESTAMP,
    ACCESS_TOKEN VARCHAR(500),
    REFRESH_TOKEN VARCHAR(500),
    IS_DELETED INT(1) DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
    NAME VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(100),
    CREATED_BY VARCHAR(40),
    CREATED_ON TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(40),
    LAST_MODIFIED_ON TIMESTAMP,
    IS_DELETED INT(1) DEFAULT 0,
    PRIMARY KEY (NAME)
);


CREATE TABLE ACCOUNT_ROLE(
	ACCOUNT_ID BIGINT NOT NULL,
	ROLE_NAME VARCHAR(40) NOT NULL
);

CREATE TABLE INVALIDATED_TOKEN (
	ID VARCHAR(500) NOT NULL,
	EXPIRY_TIME TIMESTAMP
);