server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/authentication
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: authen
    password: authen
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  secret: YourJWTSecretKeyChangeMe
  expirationMs: 3600000